name: Deploy Admin to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/admin/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'apps/admin/Dockerfile'
      - '.github/workflows/deploy-admin-cloudrun.yml'

permissions:
  contents: read
  id-token: write

env:
  REGION: ${{ vars.GCP_REGION }}
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  AR_REPOSITORY: ${{ vars.GCP_AR_REPOSITORY }}
  SERVICE: ${{ vars.CLOUD_RUN_SERVICE_ADMIN }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.ADMIN_NEXT_PUBLIC_SUPABASE_URL || secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.ADMIN_NEXT_PUBLIC_SUPABASE_ANON_KEY || secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SITE_URL: ${{ secrets.ADMIN_NEXT_PUBLIC_SITE_URL || secrets.NEXT_PUBLIC_SITE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight check (secrets/vars)
        run: |
          set -euo pipefail
          echo "Checking required secrets/vars presence (values are masked)..."
          err=0
          check() { if [ -z "$(printf "%s" "${!1:-}" | tr -d '[:space:]')" ]; then echo "::error::Missing $2"; err=1; fi; }
          check GCP_WORKLOAD_IDENTITY_PROVIDER "secret GCP_WORKLOAD_IDENTITY_PROVIDER"
          check GCP_SERVICE_ACCOUNT_EMAIL "secret GCP_SERVICE_ACCOUNT_EMAIL"
          check REGION "repository variable GCP_REGION"
          check PROJECT_ID "repository variable GCP_PROJECT_ID"
          check AR_REPOSITORY "repository variable GCP_AR_REPOSITORY"
          check SERVICE "repository variable CLOUD_RUN_SERVICE_ADMIN"
          if [ "$err" -ne 0 ]; then exit 1; fi
        env:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          REGION: ${{ env.REGION }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          AR_REPOSITORY: ${{ env.AR_REPOSITORY }}
          SERVICE: ${{ env.SERVICE }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev" --quiet

      - name: Build Docker image (admin)
        run: |
          set -euo pipefail
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build \
            -t "$IMAGE" \
            -f apps/admin/Dockerfile \
            --build-arg NEXT_PUBLIC_SUPABASE_URL="${{ env.NEXT_PUBLIC_SUPABASE_URL }}" \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            --build-arg NEXT_PUBLIC_SITE_URL="${{ env.NEXT_PUBLIC_SITE_URL }}" \
            .

      - name: Push image
        run: docker push "$IMAGE"

      - name: Deploy to Cloud Run (admin)
        run: |
          gcloud run deploy "$SERVICE" \
            --image="$IMAGE" \
            --region="$REGION" \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --set-env-vars NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY},NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

      - name: Show service URL
        run: gcloud run services describe "$SERVICE" --region="$REGION" --format='value(status.url)'

