name: build-and-deploy (deprecated)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: echo "This workflow is deprecated. Use 'Deploy Web to Cloud Run' or 'Deploy Admin to Cloud Run'."